"""add analysis_output column

Revision ID: 8c8e09665eb6
Revises: b0eb3249c97e
Create Date: 2026-06-02 21:42:10.326546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8e09665eb6'
down_revision: Union[str, None] = 'b0eb3249c97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('analysis_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'analysis_output')
    # ### end Alembic commands ###
